/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PriceEntry {
  'inStock' : boolean,
  'productId' : bigint,
  'store' : string,
  'price' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface _SERVICE {
  'addPriceEntry' : ActorMethod<[bigint, string, number, boolean], PriceEntry>,
  'createProduct' : ActorMethod<
    [string, string, string, string, Array<string>],
    Product
  >,
  'deletePriceEntry' : ActorMethod<[bigint, string], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAIInsight' : ActorMethod<[bigint], string>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getPriceEntries' : ActorMethod<[bigint], Array<PriceEntry>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updatePriceEntry' : ActorMethod<
    [bigint, string, number, boolean],
    PriceEntry
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, string, Array<string>],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];