/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceEntry = IDL.Record({
  'inStock' : IDL.Bool,
  'productId' : IDL.Nat,
  'store' : IDL.Text,
  'price' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPriceEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool],
      [PriceEntry],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Product],
      [],
    ),
  'deletePriceEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAIInsight' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getPriceEntries' : IDL.Func([IDL.Nat], [IDL.Vec(PriceEntry)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updatePriceEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool],
      [PriceEntry],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceEntry = IDL.Record({
    'inStock' : IDL.Bool,
    'productId' : IDL.Nat,
    'store' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addPriceEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool],
        [PriceEntry],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Product],
        [],
      ),
    'deletePriceEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAIInsight' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getPriceEntries' : IDL.Func([IDL.Nat], [IDL.Vec(PriceEntry)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updatePriceEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool],
        [PriceEntry],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };